design_initializr_hello:
    pattern:  /hello/{name}
    defaults: { _controller: DesignInitializrBundle:Default:hello, name: '' }

design_initializr_homepage:
    pattern:  /site/accueil
    defaults: { _controller: DesignInitializrBundle:Default:index }

design_initializr_inscription:
    pattern:  /site/inscription
    defaults: { _controller: DesignInitializrBundle:Default:inscription }
    
design_initializr_agenda:
    pattern:  /site/agenda
    defaults: { _controller: DesignInitializrBundle:Default:agenda }
    
design_initializr_contact:
    pattern:  /site/contact
    defaults: { _controller: DesignInitializrBundle:Default:contact }
    
design_initializr_admin:
    pattern:  /site/admin
    defaults: { _controller: DesignInitializrBundle:Default:admin }

design_initializr_admin_membre:
    pattern:  /site/admin/membre
    defaults: { _controller: DesignInitializrBundle:Default:adminmembres }
    
design_initializr_admin_coursStages:
    pattern:  /site/admin/coursStages
    defaults: { _controller: DesignInitializrBundle:Default:admincoursstages }
    
design_initializr_admin_modStage:
    pattern:  /site/admin/stage/{nomStage}
    defaults: { _controller: DesignInitializrBundle:Default:modStage }

design_initializr_admin_modCours:
    pattern:  /site/admin/cours/{nomCours}
    defaults: { _controller: DesignInitializrBundle:Default:modCours }

design_initializr_login:
    pattern:   /site/login
    defaults:  { _controller: DesignInitializrBundle:Default:login }

design_initializr_login_check:
    pattern:   /site/login_check
    
design_initializr_logout:
    pattern:   /site/logout
    
design_initializr_membre:
    pattern:   /site/membre
    defaults:  { _controller: DesignInitializrBundle:Default:membre }
    
design_initializr_membre_profil:
    pattern:   /site/membre/profil
    defaults:  { _controller: DesignInitializrBundle:Default:profil }
    
design_initializr_membre_cours:
    pattern:   /site/membre/cours
    defaults:  { _controller: DesignInitializrBundle:Default:cours }
    
design_initializr_inscription_stage:
    pattern:   /site/inscription/stage
    defaults:  { _controller: DesignInitializrBundle:Default:inscriptionStage }    
    
design_initializr_admin_test:
    pattern:   /site/admin/test
    defaults: { _controller: DesignInitializrBundle:Default:test }