#parameters:
#    design_initializr.example.class: Design\InitializrBundle\Example

#services:
#    design_initializr.example:
#        class: %design_initializr.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


services: 
    designinitializr_membre_repository:
        class: Design\InitializrBundle\Entity\MembreRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ["DesignInitializrBundle:Membre"]
        #factory_service: doctrine
        
    designinitializr_user:
        class: Design\InitializrBundle\Security\User
        
    designinitializr_user_provider:
        class: Design\InitializrBundle\Security\UserProvider
        factory_service: doctrine
        factory_method: getRepository
        arguments: ["DesignInitializrBundle:User"]
